spring:
  application:
    name: station-rating-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ratings_db?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: ratings_db
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8083/auth/realms/chargepoint
jwt:
  secret-key: SK0cz3mVpcfj2Bq4yJ+hiUmo+o9VN2fGzPjSIgsQHXQ=

server:
  port: 9003

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG